## Deliverable 2. Create a Customer Travel Destinations Map.

In [3]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [4]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,San Patricio,US,28.0170,-97.5169,88.52,59,51,16.22,broken clouds,2022-07-26 01:18:27
1,1,Geraldton,AU,-28.7667,114.6000,46.81,81,10,12.66,clear sky,2022-07-26 01:14:11
2,2,Santiago,CL,-33.4569,-70.6483,55.29,74,75,5.75,broken clouds,2022-07-26 01:16:41
3,3,Sume,BR,-7.6717,-36.8800,64.62,87,21,6.69,few clouds,2022-07-26 01:18:28
4,4,Severo-Kurilsk,RU,50.6789,156.1250,54.46,80,39,10.63,scattered clouds,2022-07-26 01:14:48

In [5]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
# Assign the figure variable.
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.

# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [7]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,San Patricio,US,28.0170,-97.5169,88.52,59,51,16.22,broken clouds,2022-07-26 01:18:27
5,5,Gao,ML,16.6362,1.6370,88.54,47,100,20.45,overcast clouds,2022-07-26 01:18:28
8,8,Atuona,PF,-9.8000,-139.0333,77.77,66,0,10.36,clear sky,2022-07-26 01:18:29
14,14,Phichit,TH,16.2500,100.4167,84.43,72,100,3.60,overcast clouds,2022-07-26 01:18:31
15,15,Sao Miguel Do Araguaia,BR,-13.2750,-50.1628,76.21,38,15,3.11,few clouds,2022-07-26 01:18:32
16,16,Jagatsinghapur,IN,20.2667,86.1667,79.16,83,100,5.44,overcast clouds,2022-07-26 01:18:32
18,18,Rikitea,PF,-23.1203,-134.9692,75.61,74,73,12.68,broken clouds,2022-07-26 01:17:46
22,22,Nalut,LY,30.3333,10.8500,78.60,24,0,9.62,clear sky,2022-07-26 01:18:34
24,24,Vaini,TO,-21.2000,-175.2000,78.96,83,20,9.22,few clouds,2022-07-26 01:18:34
25,25,Qui Nhon,VN,13.7667,109.2333,82.63,73,100,3.51,overcast clouds,2022-07-26 01:18:35

In [12]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isnull().sum()

#There are no empty rows

City_ID                0
City                   0
Country                0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
Date                   0
dtype: int64

In [13]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Date
0,0,San Patricio,US,28.0170,-97.5169,88.52,59,51,16.22,broken clouds,2022-07-26 01:18:27
5,5,Gao,ML,16.6362,1.6370,88.54,47,100,20.45,overcast clouds,2022-07-26 01:18:28
8,8,Atuona,PF,-9.8000,-139.0333,77.77,66,0,10.36,clear sky,2022-07-26 01:18:29
14,14,Phichit,TH,16.2500,100.4167,84.43,72,100,3.60,overcast clouds,2022-07-26 01:18:31
15,15,Sao Miguel Do Araguaia,BR,-13.2750,-50.1628,76.21,38,15,3.11,few clouds,2022-07-26 01:18:32
...,...,...,...,...,...,...,...,...,...,...,...
669,669,Neiafu,TO,-18.6500,-173.9833,79.48,61,40,12.66,scattered clouds,2022-07-26 01:22:18
677,677,Nyurba,RU,63.2842,118.3319,80.73,59,0,8.52,clear sky,2022-07-26 01:22:21
678,678,Ndioum,SN,16.5129,-14.6471,82.58,65,88,8.70,moderate rain,2022-07-26 01:22:21
681,681,Natchez,US,31.5604,-91.4032,80.82,74,0,5.75,clear sky,2022-07-26 01:22:22
682,682,Wanning,CN,18.8003,110.3967,84.40,70,5,2.66,clear sky,2022-07-26 01:22:23

In [15]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,San Patricio,US,88.52,broken clouds,28.0170,-97.5169,
5,Gao,ML,88.54,overcast clouds,16.6362,1.6370,
8,Atuona,PF,77.77,clear sky,-9.8000,-139.0333,
14,Phichit,TH,84.43,overcast clouds,16.2500,100.4167,
15,Sao Miguel Do Araguaia,BR,76.21,few clouds,-13.2750,-50.1628,
16,Jagatsinghapur,IN,79.16,overcast clouds,20.2667,86.1667,
18,Rikitea,PF,75.61,broken clouds,-23.1203,-134.9692,
22,Nalut,LY,78.60,clear sky,30.3333,10.8500,
24,Vaini,TO,78.96,few clouds,-21.2000,-175.2000,
25,Qui Nhon,VN,82.63,overcast clouds,13.7667,109.2333,

In [16]:
len(hotel_df)

264

In [19]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.

for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    
    lat = row["Lat"]
    lng = row["Lng"]
    
    # Add parameters to search for hotels with 5000 meters.
    params = {
    "location": f"{lat}, {lng}",
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
    
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError): print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [20]:
# 7. Drop the rows where there is no Hotel Name.
hotel_df.isnull().sum()

#There are no null Hotel Names.

City                   0
Country                0
Max Temp               0
Current Description    0
Lat                    0
Lng                    0
Hotel Name             0
dtype: int64

In [23]:
# 8a. Create the output File (CSV)
output_data_file = "Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_df.to_csv(output_data_file, index_label="City_ID")

In [25]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_df[["Lat", "Lng"]]

In [26]:
# 11a. Add a marker layer for each city to the map. 

max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

In [27]:
# 11b. Display the figure

fig

Figure(layout=FigureLayout(height='420px'))